// ============================================================================
// SiteSync AI: Comprehensive Synthetic Dataset (Oil India Limited Context)
// Note: All records are strictly synthetic/demonstration data for SIH26122.
// ============================================================================

import { 
  ProjectSummary, 
  WBSNode, 
  ScheduleActivity, 
  ActivityDependency, 
  NormalizedExecutionEvent, 
  ActivityMatchRecord, 
  DataConflict, 
  TerminologyMapping, 
  ActivityDNA,
  AuditRecord
} from '../types';

export const DEMO_PROJECTS: ProjectSummary[] = [
  {
    id: 'proj-oil-01',
    code: 'OIL-NE-EXP-2026',
    name: 'North-East Process Facility Expansion — Duliajan Complex',
    organization: 'Oil India Limited (OIL)',
    location: 'Duliajan, Dibrugarh District, Assam',
    startDate: '2026-01-15',
    baselineCompletionDate: '2026-11-30',
    currentForecastCompletionDate: '2026-12-18',
    status: 'AT_RISK',
    budgetINR: 1450000000, // 145 Crores
    healthScore: 68,
    plannedProgressPct: 74.5,
    actualProgressPct: 62.8,
    forecastProgressPct: 59.2,
    variancePct: -11.7,
    executionConfidencePct: 89.4,
    totalActivitiesCount: 248,
    delayedActivitiesCount: 23,
    criticalPathActivitiesCount: 18,
    unresolvedConflictsCount: 4,
    pendingReviewsCount: 7,
  },
  {
    id: 'proj-oil-02',
    code: 'OIL-NPL-BST-02',
    name: 'Numaligarh Crude Pipeline Booster Station Upgrade',
    organization: 'Oil India Limited (OIL)',
    location: 'Numaligarh, Golaghat District, Assam',
    startDate: '2026-03-01',
    baselineCompletionDate: '2026-10-15',
    currentForecastCompletionDate: '2026-10-18',
    status: 'ON_TRACK',
    budgetINR: 880000000,
    healthScore: 84,
    plannedProgressPct: 82.0,
    actualProgressPct: 80.5,
    forecastProgressPct: 79.5,
    variancePct: -1.5,
    executionConfidencePct: 94.2,
    totalActivitiesCount: 164,
    delayedActivitiesCount: 5,
    criticalPathActivitiesCount: 12,
    unresolvedConflictsCount: 1,
    pendingReviewsCount: 2,
  },
  {
    id: 'proj-oil-03',
    code: 'OIL-DGB-REF-U4',
    name: 'Digboi Heritage Field Gas Gathering Station Automation',
    organization: 'Oil India Limited (OIL)',
    location: 'Digboi, Tinsukia District, Assam',
    startDate: '2026-02-10',
    baselineCompletionDate: '2026-12-25',
    currentForecastCompletionDate: '2027-01-20',
    status: 'DELAYED',
    budgetINR: 620000000,
    healthScore: 54,
    plannedProgressPct: 66.0,
    actualProgressPct: 51.4,
    forecastProgressPct: 47.0,
    variancePct: -14.6,
    executionConfidencePct: 76.5,
    totalActivitiesCount: 192,
    delayedActivitiesCount: 31,
    criticalPathActivitiesCount: 16,
    unresolvedConflictsCount: 6,
    pendingReviewsCount: 12,
  },
];

export const DEMO_WBS_NODES: WBSNode[] = [
  { id: 'wbs-1', projectId: 'proj-oil-01', code: '1.0', name: 'North-East Process Facility Expansion', level: 'L1', discipline: 'Mechanical' },
  { id: 'wbs-1.1', projectId: 'proj-oil-01', code: '1.1', name: 'Area 04 — Gas Compression Unit (GCU)', level: 'L2', parentId: 'wbs-1', discipline: 'Mechanical' },
  { id: 'wbs-1.1.1', projectId: 'proj-oil-01', code: '1.1.1', name: 'Civil & Structural Foundations', level: 'L3', parentId: 'wbs-1.1', discipline: 'Civil' },
  { id: 'wbs-1.1.2', projectId: 'proj-oil-01', code: '1.1.2', name: 'Process Piping & Spool Integration', level: 'L3', parentId: 'wbs-1.1', discipline: 'Piping' },
  { id: 'wbs-1.1.3', projectId: 'proj-oil-01', code: '1.1.3', name: 'Electrical Power & Tray Subsystems', level: 'L3', parentId: 'wbs-1.1', discipline: 'Electrical' },
  { id: 'wbs-1.1.4', projectId: 'proj-oil-01', code: '1.1.4', name: 'Compressor Package Mechanical Installation', level: 'L3', parentId: 'wbs-1.1', discipline: 'Rotating Equipment' },
  { id: 'wbs-1.1.5', projectId: 'proj-oil-01', code: '1.1.5', name: 'Instrumentation & SCADA Integration', level: 'L3', parentId: 'wbs-1.1', discipline: 'Instrumentation' },

  // L4 Nodes under Area 04 Piping
  { id: 'wbs-1.1.2.1', projectId: 'proj-oil-01', code: '1.1.2.1', name: 'Aboveground Process Piping Erection', level: 'L4', parentId: 'wbs-1.1.2', discipline: 'Piping' },
  { id: 'wbs-1.1.2.2', projectId: 'proj-oil-01', code: '1.1.2.2', name: 'Pipe Rack Spool Transportation & Rigging', level: 'L4', parentId: 'wbs-1.1.2', discipline: 'Piping' },
  
  // L5 Nodes
  { id: 'wbs-1.1.2.1.1', projectId: 'proj-oil-01', code: '1.1.2.1.1', name: 'Compressor Suction & Discharge Spool Installation', level: 'L5', parentId: 'wbs-1.1.2.1', discipline: 'Piping' },
  { id: 'wbs-1.1.1.1.1', projectId: 'proj-oil-01', code: '1.1.1.1.1', name: 'Compressor Plinth & Footing Concreting', level: 'L5', parentId: 'wbs-1.1.1', discipline: 'Civil' },
  { id: 'wbs-1.1.3.1.1', projectId: 'proj-oil-01', code: '1.1.3.1.1', name: 'MCC to Compressor Cable Tray Run', level: 'L5', parentId: 'wbs-1.1.3', discipline: 'Electrical' },
  { id: 'wbs-1.1.4.1.1', projectId: 'proj-oil-01', code: '1.1.4.1.1', name: 'Compressor Skid Alignment & Grouting', level: 'L5', parentId: 'wbs-1.1.4', discipline: 'Rotating Equipment' },
];

export const DEMO_ACTIVITIES: ScheduleActivity[] = [
  // PIPING
  {
    id: 'act-pipe-0142',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.2.1.1',
    activityCode: 'PIPE-ERECT-L6-0142',
    name: 'Erection of 12-inch process line at compressor area',
    level: 'L6',
    discipline: 'Piping',
    location: 'Area 04 — Gas Compressor Unit',
    responsibleContractor: 'Assam Industrial Engineering Services (AIES)',
    plannedStart: '2026-09-18',
    plannedFinish: '2026-09-27',
    plannedDurationDays: 9,
    baselinePercent: 100,
    actualStart: '2026-09-20',
    actualFinish: undefined,
    actualDurationDays: 9,
    actualPercent: 78,
    forecastFinish: '2026-10-04',
    forecastVarianceDays: 7, // 7 days delayed
    quantity: 48,
    unit: 'meters',
    installedQuantity: 37.5,
    status: 'DELAYED',
    isCriticalPath: true,
    isMilestone: false,
    matchConfidence: 94,
    lastUpdateDate: '2026-09-28',
    lastSourceId: 'src-voice-001',
    lastReportSentence: '12 inch spool erected near compressor section.',
    historicalBenchmarkDays: 7,
    historicalVarianceDays: 1.4,
    commonDelayCause: 'Material delivery & crane rigging availability',
    lifecycleHistory: [
      {
        id: 'life-p142-1',
        activityId: 'act-pipe-0142',
        activityCode: 'PIPE-ERECT-L6-0142',
        date: '2026-09-20',
        eventType: 'START',
        progressPct: 15,
        rawReport: 'Spool rigging started at compressor bay. Mobile crane 50T mobilized.',
        reportedBy: 'Bikash Gogoi (Senior Piping Supervisor)',
        sourceRef: 'Field Voice Log #089',
        durationToDateDays: 1,
        velocityMetric: '15%/day'
      },
      {
        id: 'life-p142-2',
        activityId: 'act-pipe-0142',
        activityCode: 'PIPE-ERECT-L6-0142',
        date: '2026-09-24',
        eventType: 'PROGRESS',
        progressPct: 45,
        rawReport: 'Spool placement reached 45%. 22 meters of 12-inch line aligned on rack.',
        reportedBy: 'Bikash Gogoi (Senior Piping Supervisor)',
        sourceRef: 'Site Daily Log #104',
        durationToDateDays: 5,
        velocityMetric: '9%/day'
      },
      {
        id: 'life-p142-3',
        activityId: 'act-pipe-0142',
        activityCode: 'PIPE-ERECT-L6-0142',
        date: '2026-09-28',
        eventType: 'PROGRESS',
        progressPct: 78,
        rawReport: '12 inch spool erected near compressor section. Around 18m completed between 9:00 AM and 4:30 PM.',
        reportedBy: 'Bikash Gogoi (Senior Piping Supervisor)',
        sourceRef: 'Voice Update #001',
        durationToDateDays: 9,
        velocityMetric: '8.7%/day'
      }
    ],
    subtasks: [
      { id: 'sub-p142-1', activityId: 'act-pipe-0142', code: 'PIPE-0142.1', name: 'Spool Transportation & Rigging Crane Setup', weightPct: 15, progressPct: 100, status: 'COMPLETED' },
      { id: 'sub-p142-2', activityId: 'act-pipe-0142', code: 'PIPE-0142.2', name: 'Pipe Spool Hoisting & Alignment on Rack', weightPct: 35, progressPct: 90, status: 'IN_PROGRESS' },
      { id: 'sub-p142-3', activityId: 'act-pipe-0142', code: 'PIPE-0142.3', name: 'Joint Fit-Up & Root Pass TIG Tack Welding', weightPct: 25, progressPct: 65, status: 'IN_PROGRESS' },
      { id: 'sub-p142-4', activityId: 'act-pipe-0142', code: 'PIPE-0142.4', name: 'Hot Pass & Cap Pass Shielded Arc Welding', weightPct: 15, progressPct: 40, status: 'IN_PROGRESS' },
      { id: 'sub-p142-5', activityId: 'act-pipe-0142', code: 'PIPE-0142.5', name: 'Visual QC & Radiographic NDT Testing', weightPct: 10, progressPct: 0, status: 'NOT_STARTED' }
    ]
  },
  {
    id: 'act-pipe-0143',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.2.1.1',
    activityCode: 'PIPE-FITUP-L6-0143',
    name: 'Fit-up and pre-welding inspection of 12-inch discharge line',
    level: 'L6',
    discipline: 'Piping',
    location: 'Area 04 — Gas Compressor Unit',
    responsibleContractor: 'Assam Industrial Engineering Services (AIES)',
    plannedStart: '2026-09-24',
    plannedFinish: '2026-09-29',
    plannedDurationDays: 5,
    baselinePercent: 80,
    actualStart: '2026-09-26',
    actualFinish: undefined,
    actualDurationDays: 3,
    actualPercent: 40,
    forecastFinish: '2026-10-06',
    forecastVarianceDays: 7,
    quantity: 18,
    unit: 'joints',
    installedQuantity: 7,
    status: 'IN_PROGRESS',
    isCriticalPath: true,
    isMilestone: false,
    matchConfidence: 89,
    historicalBenchmarkDays: 4.5,
    historicalVarianceDays: 1.1,
    commonDelayCause: 'Welder certification and NDT clearance',
  },
  {
    id: 'act-pipe-0144',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.2.1.1',
    activityCode: 'PIPE-HYDRO-L6-0144',
    name: 'Hydrostatic pressure testing of 12-inch process headers',
    level: 'L6',
    discipline: 'Piping',
    location: 'Area 04 — Gas Compressor Unit',
    responsibleContractor: 'Assam Industrial Engineering Services (AIES)',
    plannedStart: '2026-09-30',
    plannedFinish: '2026-10-05',
    plannedDurationDays: 5,
    baselinePercent: 0,
    actualPercent: 0,
    forecastFinish: '2026-10-12',
    forecastVarianceDays: 7,
    quantity: 1,
    unit: 'loop',
    installedQuantity: 0,
    status: 'NOT_STARTED',
    isCriticalPath: true,
    isMilestone: true,
    historicalBenchmarkDays: 5.2,
    historicalVarianceDays: 0.8,
    commonDelayCause: 'Water availability and test manifold valve seating',
  },
  {
    id: 'act-pipe-0191',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.2.1.1',
    activityCode: 'PIPE-ERECT-L6-0191',
    name: 'Erection of 8-inch bypass line at scrubber skid',
    level: 'L6',
    discipline: 'Piping',
    location: 'Area 04 — Scrubber Skid',
    responsibleContractor: 'Brahmaputra Pipelines Ltd',
    plannedStart: '2026-09-22',
    plannedFinish: '2026-09-28',
    plannedDurationDays: 6,
    baselinePercent: 100,
    actualStart: '2026-09-22',
    actualFinish: '2026-09-28',
    actualDurationDays: 6,
    actualPercent: 100,
    forecastFinish: '2026-09-28',
    forecastVarianceDays: 0,
    quantity: 32,
    unit: 'meters',
    installedQuantity: 32,
    status: 'COMPLETED',
    isCriticalPath: false,
    isMilestone: false,
    historicalBenchmarkDays: 6.0,
    historicalVarianceDays: 0.2,
  },

  // CIVIL
  {
    id: 'act-civ-0102',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.1.1.1',
    activityCode: 'CIV-FOUND-L6-0102',
    name: 'Foundation F-102 concrete pouring and curing',
    level: 'L6',
    discipline: 'Civil',
    location: 'Area 04 — Compressor Bay 2',
    responsibleContractor: 'North-East Infrastructure & Infra Corp',
    plannedStart: '2026-09-12',
    plannedFinish: '2026-09-25',
    plannedDurationDays: 13,
    baselinePercent: 100,
    actualStart: '2026-09-14',
    actualFinish: '2026-09-26',
    actualDurationDays: 12,
    actualPercent: 100,
    forecastFinish: '2026-09-26',
    forecastVarianceDays: 1,
    quantity: 75,
    unit: 'm3',
    installedQuantity: 75,
    status: 'COMPLETED',
    isCriticalPath: true,
    isMilestone: false,
    matchConfidence: 98,
    historicalBenchmarkDays: 12.5,
    historicalVarianceDays: 1.5,
    commonDelayCause: 'Batching plant logistics & heavy monsoon downpours',
    lifecycleHistory: [
      {
        id: 'life-c102-1',
        activityId: 'act-civ-0102',
        activityCode: 'CIV-FOUND-L6-0102',
        date: '2026-09-14',
        eventType: 'START',
        progressPct: 15,
        rawReport: 'F-102 excavation and mud mat PCC casting commenced.',
        reportedBy: 'Site Civil Foreman',
        sourceRef: 'Civil Shift Diary #044',
        durationToDateDays: 1,
        velocityMetric: '15%/day'
      },
      {
        id: 'life-c102-2',
        activityId: 'act-civ-0102',
        activityCode: 'CIV-FOUND-L6-0102',
        date: '2026-09-20',
        eventType: 'PROGRESS',
        progressPct: 60,
        rawReport: 'Rebar cage tying and shuttering forms erected. Plinth anchor template secured.',
        reportedBy: 'Civil Site Inspector',
        sourceRef: 'Inspection Report IR-CIV-08',
        durationToDateDays: 7,
        velocityMetric: '8.5%/day'
      },
      {
        id: 'life-c102-3',
        activityId: 'act-civ-0102',
        activityCode: 'CIV-FOUND-L6-0102',
        date: '2026-09-26',
        eventType: 'FINISH',
        progressPct: 100,
        rawReport: 'Concrete pouring for foundation F-102 completed at 17:00. Batching plant delivered 75 m3 grade M35 concrete.',
        reportedBy: 'DPR Daily Compilation Desk',
        sourceRef: 'DPR Shift #1 (#evt-002)',
        durationToDateDays: 13,
        velocityMetric: '7.7%/day'
      }
    ],
    subtasks: [
      { id: 'sub-c102-1', activityId: 'act-civ-0102', code: 'CIV-0102.1', name: 'Excavation, Shoring & Dewatering', weightPct: 20, progressPct: 100, status: 'COMPLETED' },
      { id: 'sub-c102-2', activityId: 'act-civ-0102', code: 'CIV-0102.2', name: 'PCC Mud Mat & Plinth Marking', weightPct: 15, progressPct: 100, status: 'COMPLETED' },
      { id: 'sub-c102-3', activityId: 'act-civ-0102', code: 'CIV-0102.3', name: 'Rebar Cage Tying & Bolt Embedment', weightPct: 30, progressPct: 100, status: 'COMPLETED' },
      { id: 'sub-c102-4', activityId: 'act-civ-0102', code: 'CIV-0102.4', name: 'Shuttering Formwork Assembly', weightPct: 15, progressPct: 100, status: 'COMPLETED' },
      { id: 'sub-c102-5', activityId: 'act-civ-0102', code: 'CIV-0102.5', name: 'M35 Concrete Pouring & Curing', weightPct: 20, progressPct: 100, status: 'COMPLETED' }
    ]
  },
  {
    id: 'act-civ-0103',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.1.1.1',
    activityCode: 'CIV-PLINTH-L6-0103',
    name: 'Anchor bolt grouting and pocket curing for foundation F-102',
    level: 'L6',
    discipline: 'Civil',
    location: 'Area 04 — Compressor Bay 2',
    responsibleContractor: 'North-East Infrastructure & Infra Corp',
    plannedStart: '2026-09-26',
    plannedFinish: '2026-09-29',
    plannedDurationDays: 3,
    baselinePercent: 70,
    actualStart: '2026-09-27',
    actualFinish: undefined,
    actualDurationDays: 2,
    actualPercent: 65,
    forecastFinish: '2026-09-30',
    forecastVarianceDays: 1,
    quantity: 16,
    unit: 'pockets',
    installedQuantity: 10,
    status: 'IN_PROGRESS',
    isCriticalPath: true,
    isMilestone: false,
    historicalBenchmarkDays: 3.0,
    historicalVarianceDays: 0.3,
  },

  // ELECTRICAL
  {
    id: 'act-elec-0102',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.3.1.1',
    activityCode: 'ELEC-TRAY-L6-0102',
    name: 'Cable tray installation at Unit 2 compressor bay',
    level: 'L6',
    discipline: 'Electrical',
    location: 'Area 04 — Cable Trench Way A',
    responsibleContractor: 'Eastern Power Grid Projects',
    plannedStart: '2026-09-25',
    plannedFinish: '2026-10-04',
    plannedDurationDays: 9,
    baselinePercent: 40,
    actualStart: '2026-09-27',
    actualFinish: undefined,
    actualDurationDays: 2,
    actualPercent: 25,
    forecastFinish: '2026-10-08',
    forecastVarianceDays: 4,
    quantity: 120,
    unit: 'meters',
    installedQuantity: 30,
    status: 'IN_PROGRESS',
    isCriticalPath: false,
    isMilestone: false,
    matchConfidence: 92,
    historicalBenchmarkDays: 8.5,
    historicalVarianceDays: 0.9,
    commonDelayCause: 'Hold-up awaiting civil clearance and bracket fabrications',
  },
  {
    id: 'act-elec-0114',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.3.1.1',
    activityCode: 'ELEC-SUPP-L6-0114',
    name: 'Cable support bracket welding on structural stanchions',
    level: 'L6',
    discipline: 'Electrical',
    location: 'Area 04 — Cable Trench Way A',
    responsibleContractor: 'Eastern Power Grid Projects',
    plannedStart: '2026-09-22',
    plannedFinish: '2026-09-26',
    plannedDurationDays: 4,
    baselinePercent: 100,
    actualStart: '2026-09-23',
    actualFinish: '2026-09-27',
    actualDurationDays: 4,
    actualPercent: 100,
    forecastFinish: '2026-09-27',
    forecastVarianceDays: 1,
    quantity: 45,
    unit: 'nos',
    installedQuantity: 45,
    status: 'COMPLETED',
    isCriticalPath: false,
    isMilestone: false,
  },

  // MECHANICAL / ROTATING
  {
    id: 'act-mech-0310',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.4.1.1',
    activityCode: 'MECH-ALIGN-L6-0310',
    name: 'Reciprocating compressor C-101 motor-compressor shaft alignment',
    level: 'L6',
    discipline: 'Rotating Equipment',
    location: 'Area 04 — Compressor House',
    responsibleContractor: 'BHEL Heavy Machinery Division',
    plannedStart: '2026-10-01',
    plannedFinish: '2026-10-08',
    plannedDurationDays: 7,
    baselinePercent: 0,
    actualPercent: 0,
    forecastFinish: '2026-10-15',
    forecastVarianceDays: 7,
    quantity: 1,
    unit: 'package',
    installedQuantity: 0,
    status: 'NOT_STARTED',
    isCriticalPath: true,
    isMilestone: false,
    historicalBenchmarkDays: 7.2,
    historicalVarianceDays: 1.8,
    commonDelayCause: 'Laser alignment tooling recalibration & shim pack delays',
  },
  {
    id: 'act-mech-0320',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.4.1.1',
    activityCode: 'MECH-NO-LOAD-L6-0320',
    name: 'Uncoupled solo motor run & vibration signature baseline',
    level: 'L6',
    discipline: 'Rotating Equipment',
    location: 'Area 04 — Compressor House',
    responsibleContractor: 'BHEL Heavy Machinery Division',
    plannedStart: '2026-10-09',
    plannedFinish: '2026-10-12',
    plannedDurationDays: 3,
    baselinePercent: 0,
    actualPercent: 0,
    forecastFinish: '2026-10-18',
    forecastVarianceDays: 6,
    quantity: 1,
    unit: 'test',
    installedQuantity: 0,
    status: 'NOT_STARTED',
    isCriticalPath: true,
    isMilestone: true,
  },

  // INSTRUMENTATION
  {
    id: 'act-inst-0205',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.5',
    activityCode: 'INST-CALIB-L6-0205',
    name: 'Suction pressure transmitter PT-401A/B bench calibration',
    level: 'L6',
    discipline: 'Instrumentation',
    location: 'Area 04 — Field Instrument Lab',
    responsibleContractor: 'Yokogawa India Instrumentation Service',
    plannedStart: '2026-09-24',
    plannedFinish: '2026-09-27',
    plannedDurationDays: 3,
    baselinePercent: 100,
    actualStart: '2026-09-25',
    actualFinish: '2026-09-28',
    actualDurationDays: 3,
    actualPercent: 100,
    forecastFinish: '2026-09-28',
    forecastVarianceDays: 1,
    quantity: 4,
    unit: 'nos',
    installedQuantity: 4,
    status: 'COMPLETED',
    isCriticalPath: false,
    isMilestone: false,
  },
  {
    id: 'act-inst-0206',
    projectId: 'proj-oil-01',
    wbsId: 'wbs-1.1.5',
    activityCode: 'INST-HOOKUP-L6-0206',
    name: 'Tubing hookup and impulse line impulse testing for PT-401',
    level: 'L6',
    discipline: 'Instrumentation',
    location: 'Area 04 — Compressor Bay 2',
    responsibleContractor: 'Yokogawa India Instrumentation Service',
    plannedStart: '2026-09-28',
    plannedFinish: '2026-10-02',
    plannedDurationDays: 4,
    baselinePercent: 20,
    actualStart: '2026-09-29',
    actualPercent: 10,
    forecastFinish: '2026-10-05',
    forecastVarianceDays: 3,
    quantity: 12,
    unit: 'meters',
    installedQuantity: 2,
    status: 'IN_PROGRESS',
    isCriticalPath: false,
    isMilestone: false,
  }
];

export const DEMO_DEPENDENCIES: ActivityDependency[] = [
  { id: 'dep-1', predecessorId: 'act-civ-0102', successorId: 'act-civ-0103', type: 'FS', lagDays: 0 },
  { id: 'dep-2', predecessorId: 'act-civ-0103', successorId: 'act-pipe-0142', type: 'FS', lagDays: 1 },
  { id: 'dep-3', predecessorId: 'act-pipe-0142', successorId: 'act-pipe-0143', type: 'SS', lagDays: 4 },
  { id: 'dep-4', predecessorId: 'act-pipe-0143', successorId: 'act-pipe-0144', type: 'FS', lagDays: 1 },
  { id: 'dep-5', predecessorId: 'act-pipe-0142', successorId: 'act-mech-0310', type: 'FS', lagDays: 2 },
  { id: 'dep-6', predecessorId: 'act-mech-0310', successorId: 'act-mech-0320', type: 'FS', lagDays: 1 },
  { id: 'dep-7', predecessorId: 'act-elec-0114', successorId: 'act-elec-0102', type: 'FS', lagDays: 0 },
  { id: 'dep-8', predecessorId: 'act-inst-0205', successorId: 'act-inst-0206', type: 'FS', lagDays: 0 },
];

export const DEMO_FIELD_EVENTS: NormalizedExecutionEvent[] = [
  {
    eventId: 'evt-001',
    projectId: 'proj-oil-01',
    sourceId: 'src-voice-001',
    sourceType: 'VOICE',
    reportedBy: 'Bikash Gogoi (Senior Piping Supervisor)',
    reporterRole: 'supervisor',
    reportedDate: '2026-09-28',
    rawText: '12 inch spool erected near compressor section today. Around 18 meters completed between 9:00 AM and 4:30 PM.',
    activityDescription: '12-inch spool erection near compressor section',
    discipline: 'Piping',
    action: 'erected',
    assetOrComponent: '12-inch spool',
    location: 'Compressor section (Area 04)',
    startTime: '09:00',
    endTime: '16:30',
    quantity: 18,
    unit: 'meters',
    percentComplete: 78,
    statusReported: 'IN_PROGRESS',
    contractor: 'AIES',
    equipment: ['Hydraulic Mobile Crane 50T (OIL-EQ-104)', 'Scaffolding Unit #4'],
    manpowerCount: 8,
    photoUrl: '/images/piping-spool-erection.jpg',
    extractionConfidence: 96,
    createdAt: '2026-09-28T17:15:00Z',
  },
  {
    eventId: 'evt-002',
    projectId: 'proj-oil-01',
    sourceId: 'src-dpr-001',
    sourceType: 'DPR',
    reportedBy: 'DPR Daily Compilation Desk',
    reporterRole: 'planner',
    reportedDate: '2026-09-28',
    rawText: 'Concrete pouring for foundation F-102 completed at 17:00. Batching plant delivered 75 m3 grade M35 concrete. Plinth bolts aligned.',
    activityDescription: 'Foundation F-102 concrete pouring',
    discipline: 'Civil',
    action: 'poured',
    assetOrComponent: 'Foundation F-102',
    location: 'Compressor Bay 2',
    startTime: '08:30',
    endTime: '17:00',
    quantity: 75,
    unit: 'm3',
    percentComplete: 100,
    statusReported: 'COMPLETED',
    contractor: 'North-East Infrastructure',
    equipment: ['Transit Mixer TM-04', 'Concrete Pump CP-02'],
    manpowerCount: 14,
    photoUrl: '/images/concrete-foundation-pouring.jpg',
    extractionConfidence: 98,
    createdAt: '2026-09-28T19:30:00Z',
  },
  {
    eventId: 'evt-003',
    projectId: 'proj-oil-01',
    sourceId: 'src-text-003',
    sourceType: 'TEXT',
    reportedBy: 'Debajit Baruah (Electrical Engineer)',
    reporterRole: 'supervisor',
    reportedDate: '2026-09-28',
    rawText: 'Electrical cable tray installation in unit two started this morning. 30 meters fixed before rain interruption at 15:00.',
    activityDescription: 'Cable tray installation in Unit 2',
    discipline: 'Electrical',
    action: 'installed',
    assetOrComponent: 'Cable tray',
    location: 'Unit 2 compressor bay',
    startTime: '08:45',
    endTime: '15:00',
    quantity: 30,
    unit: 'meters',
    percentComplete: 25,
    statusReported: 'IN_PROGRESS',
    contractor: 'Eastern Power Grid Projects',
    delayReason: 'Precipitation/monsoon rain hold-up at 15:00',
    photoUrl: '/images/electrical-cable-tray.jpg',
    extractionConfidence: 94,
    createdAt: '2026-09-28T15:45:00Z',
  },
  {
    eventId: 'evt-004',
    projectId: 'proj-oil-01',
    sourceId: 'src-sheet-004',
    sourceType: 'SPREADSHEET',
    reportedBy: 'Site Subcontractor Daily Tracker (Excel upload)',
    reporterRole: 'supervisor',
    reportedDate: '2026-09-28',
    rawText: 'Item row 14: Spool erection at GCU 12-inch line reported 70% complete (Progress conflict vs supervisor report).',
    activityDescription: 'Spool erection at GCU 12-inch line',
    discipline: 'Piping',
    action: 'erected',
    assetOrComponent: '12-inch GCU spool',
    location: 'GCU Area',
    percentComplete: 70, // Contradicts 78%
    statusReported: 'IN_PROGRESS',
    contractor: 'AIES',
    photoUrl: '/images/subcon-pipeline-survey.jpg',
    extractionConfidence: 91,
    createdAt: '2026-09-28T18:00:00Z',
  },
  {
    eventId: 'evt-005',
    projectId: 'proj-oil-01',
    sourceId: 'src-voice-005',
    sourceType: 'VOICE',
    reportedBy: 'Bikash Gogoi (Senior Piping Supervisor)',
    reporterRole: 'supervisor',
    reportedDate: '2026-09-29',
    rawText: 'Temporary drainage channel created near Unit 4 because of flooding. Excavator deployed for 6 hours to divert stormwater away from open trenches.',
    activityDescription: 'Temporary drainage channel excavation at Unit 4',
    discipline: 'Civil',
    action: 'excavated',
    assetOrComponent: 'Temporary stormwater trench',
    location: 'Area 04 — Unit 4 Corridor',
    percentComplete: 100,
    statusReported: 'COMPLETED',
    contractor: 'Emergency Site Crew',
    photoUrl: '/images/concrete-foundation-pouring.jpg',
    extractionConfidence: 92,
    createdAt: '2026-09-29T11:30:00Z',
  }
];

export const DEMO_MATCHES: ActivityMatchRecord[] = [
  {
    matchId: 'match-001',
    eventId: 'evt-001',
    selectedActivityId: 'act-pipe-0142',
    confidence: 94,
    status: 'APPROVED',
    plannerNotes: 'Approved by Lead Planner P. Saikia. Matched to 12-inch compressor piping line.',
    reviewedBy: 'Pranjal Saikia (Lead Project Planner)',
    reviewedAt: '2026-09-28T18:10:00Z',
    appliedToSchedule: true,
    candidates: [
      {
        activityId: 'act-pipe-0142',
        activityCode: 'PIPE-ERECT-L6-0142',
        activityName: 'Erection of 12-inch process line at compressor area',
        discipline: 'Piping',
        wbsHierarchy: 'GCU > Piping > Compressor Spools',
        lexicalScore: 0.92,
        fuzzyScore: 0.95,
        semanticScore: 0.96,
        contextScore: 0.94,
        temporalScore: 0.93,
        finalConfidence: 94,
        confidenceTier: 'HIGH',
        explanationPoints: [
          { passed: true, text: '12-inch dimension exactly matches schedule specification' },
          { passed: true, text: 'Spool / erection technical terminology matches L6 scope' },
          { passed: true, text: 'Compressor area matches physical plant location (Area 04)' },
          { passed: true, text: 'Piping discipline perfectly aligned' },
          { passed: true, text: 'Date falls inside planned execution window' },
          { passed: true, text: 'Predecessor (Foundation Plinth F-102) is verified complete' },
          { passed: true, text: 'Matches project terminology mapping: "spool erection" -> PIPE-ERECT-L6-0142' }
        ]
      },
      {
        activityId: 'act-pipe-0191',
        activityCode: 'PIPE-ERECT-L6-0191',
        activityName: 'Erection of 8-inch bypass line at scrubber skid',
        discipline: 'Piping',
        wbsHierarchy: 'GCU > Piping > Scrubber Bypass',
        lexicalScore: 0.65,
        fuzzyScore: 0.70,
        semanticScore: 0.74,
        contextScore: 0.68,
        temporalScore: 0.85,
        finalConfidence: 72,
        confidenceTier: 'MEDIUM',
        explanationPoints: [
          { passed: false, text: 'Diameter mismatch: reported 12-inch vs 8-inch specification' },
          { passed: false, text: 'Location mismatch: Compressor bay vs Scrubber skid' },
          { passed: true, text: 'Action (erection) matches discipline' },
          { passed: false, text: 'Activity already marked 100% completed in schedule' }
        ]
      },
      {
        activityId: 'act-pipe-0143',
        activityCode: 'PIPE-FITUP-L6-0143',
        activityName: 'Fit-up and pre-welding inspection of 12-inch discharge line',
        discipline: 'Piping',
        wbsHierarchy: 'GCU > Piping > Discharge Header',
        lexicalScore: 0.45,
        fuzzyScore: 0.50,
        semanticScore: 0.52,
        contextScore: 0.55,
        temporalScore: 0.60,
        finalConfidence: 48,
        confidenceTier: 'LOW',
        explanationPoints: [
          { passed: false, text: 'Action mismatch: reported erection vs fit-up/welding inspection' },
          { passed: true, text: '12-inch process line diameter matched' }
        ]
      }
    ]
  },
  {
    matchId: 'match-002',
    eventId: 'evt-003',
    selectedActivityId: 'act-elec-0102',
    confidence: 92,
    status: 'PENDING_REVIEW',
    appliedToSchedule: false,
    candidates: [
      {
        activityId: 'act-elec-0102',
        activityCode: 'ELEC-TRAY-L6-0102',
        activityName: 'Cable tray installation at Unit 2 compressor bay',
        discipline: 'Electrical',
        wbsHierarchy: 'GCU > Electrical > Cable Tray',
        lexicalScore: 0.90,
        fuzzyScore: 0.92,
        semanticScore: 0.94,
        contextScore: 0.91,
        temporalScore: 0.93,
        finalConfidence: 92,
        confidenceTier: 'HIGH',
        explanationPoints: [
          { passed: true, text: 'Cable tray component matches electrical L6 item' },
          { passed: true, text: 'Unit 2 compressor location verified' },
          { passed: true, text: 'Predecessor cable support brackets (ELEC-SUPP-L6-0114) completed' },
          { passed: true, text: 'Quantity (30m) conforms with 120m activity budget' }
        ]
      },
      {
        activityId: 'act-elec-0114',
        activityCode: 'ELEC-SUPP-L6-0114',
        activityName: 'Cable support bracket welding on structural stanchions',
        discipline: 'Electrical',
        wbsHierarchy: 'GCU > Electrical > Support Brackets',
        lexicalScore: 0.62,
        fuzzyScore: 0.65,
        semanticScore: 0.68,
        contextScore: 0.70,
        temporalScore: 0.65,
        finalConfidence: 66,
        confidenceTier: 'LOW',
        explanationPoints: [
          { passed: false, text: 'Component mismatch: reported tray vs bracket welding' },
          { passed: false, text: 'Activity already fully executed' }
        ]
      }
    ]
  },
  {
    matchId: 'match-003',
    eventId: 'evt-002',
    selectedActivityId: 'act-civ-0102',
    confidence: 98,
    status: 'APPROVED',
    plannerNotes: 'Foundation F-102 pouring verified with batching plant slips. 75 m3 Grade M35 concrete cubes sampled.',
    reviewedBy: 'Pranjal Saikia (Lead Project Planner)',
    reviewedAt: '2026-09-28T19:45:00Z',
    appliedToSchedule: true,
    candidates: [
      {
        activityId: 'act-civ-0102',
        activityCode: 'CIV-FOUND-L6-0102',
        activityName: 'Foundation F-102 concrete pouring and curing',
        discipline: 'Civil',
        wbsHierarchy: 'GCU > Civil Works > Foundation F-102',
        lexicalScore: 0.98,
        fuzzyScore: 0.99,
        semanticScore: 0.97,
        contextScore: 0.98,
        temporalScore: 0.98,
        finalConfidence: 98,
        confidenceTier: 'HIGH',
        explanationPoints: [
          { passed: true, text: 'Foundation F-102 matches WBS asset nomenclature' },
          { passed: true, text: 'Pouring volume (75 m3) exactly matches planned design envelope' },
          { passed: true, text: 'Excavation & rebar inspection prerequisites verified complete' },
          { passed: true, text: 'Digboi Compressor Bay 2 location coordinates verified' }
        ]
      },
      {
        activityId: 'act-civ-0103',
        activityCode: 'CIV-PLINTH-L6-0103',
        activityName: 'Anchor bolt grouting and pocket curing for foundation F-102',
        discipline: 'Civil',
        wbsHierarchy: 'GCU > Civil Works > Foundation Plinth',
        lexicalScore: 0.70,
        fuzzyScore: 0.74,
        semanticScore: 0.75,
        contextScore: 0.72,
        temporalScore: 0.60,
        finalConfidence: 71,
        confidenceTier: 'MEDIUM',
        explanationPoints: [
          { passed: false, text: 'Successor activity: requires 48hr initial concrete set before anchor grouting' },
          { passed: true, text: 'Foundation F-102 component matched' }
        ]
      }
    ]
  },
  {
    matchId: 'match-004',
    eventId: 'evt-004',
    selectedActivityId: 'act-pipe-0142',
    confidence: 88,
    status: 'PENDING_REVIEW',
    plannerNotes: 'Subcontractor spreadsheet claims 70% vs supervisor voice claim of 78%. Flagged under Dispute Resolution.',
    appliedToSchedule: false,
    candidates: [
      {
        activityId: 'act-pipe-0142',
        activityCode: 'PIPE-ERECT-L6-0142',
        activityName: 'Erection of 12-inch process line at compressor area',
        discipline: 'Piping',
        wbsHierarchy: 'GCU > Piping > Compressor Spools',
        lexicalScore: 0.88,
        fuzzyScore: 0.89,
        semanticScore: 0.86,
        contextScore: 0.89,
        temporalScore: 0.90,
        finalConfidence: 88,
        confidenceTier: 'HIGH',
        explanationPoints: [
          { passed: true, text: '12-inch GCU spool item matches line specification' },
          { passed: true, text: 'Piping discipline matches AIES scope of work' },
          { passed: false, text: 'Progress contradiction: 70% reported vs 78% supervisor log' }
        ]
      },
      {
        activityId: 'act-pipe-0143',
        activityCode: 'PIPE-FITUP-L6-0143',
        activityName: 'Fit-up and pre-welding inspection of 12-inch discharge line',
        discipline: 'Piping',
        wbsHierarchy: 'GCU > Piping > Discharge Header',
        lexicalScore: 0.55,
        fuzzyScore: 0.60,
        semanticScore: 0.62,
        contextScore: 0.58,
        temporalScore: 0.70,
        finalConfidence: 61,
        confidenceTier: 'LOW',
        explanationPoints: [
          { passed: false, text: 'Action mismatch: erection vs fit-up inspection' }
        ]
      }
    ]
  },
  {
    matchId: 'match-005',
    eventId: 'evt-005',
    selectedActivityId: '',
    confidence: 38,
    status: 'UNPLANNED_WORK',
    isUnplanned: true,
    unplannedCategory: 'NON_SCHEDULE_SUPPORT',
    plannerNotes: 'Flagged by Unplanned Work Detector: Out-of-baseline stormwater protection work. No matching P6 baseline activity found.',
    appliedToSchedule: false,
    candidates: [
      {
        activityId: 'act-civ-0102',
        activityCode: 'CIV-FOUND-L6-0102',
        activityName: 'Foundation F-102 concrete pouring and curing',
        discipline: 'Civil',
        wbsHierarchy: 'GCU > Civil Works > Foundation F-102',
        lexicalScore: 0.18,
        fuzzyScore: 0.25,
        semanticScore: 0.32,
        contextScore: 0.40,
        temporalScore: 0.70,
        finalConfidence: 38,
        confidenceTier: 'LOW',
        explanationPoints: [
          { passed: false, text: 'No schedule match: temporary drainage channel is absent from baseline P6 WBS' },
          { passed: true, text: 'Civil discipline aligned with emergency excavation' },
          { passed: false, text: 'Confidence below 65% threshold: safely routed to Unplanned Work Queue' }
        ]
      }
    ]
  }
];

export const DEMO_CONFLICTS: DataConflict[] = [
  {
    id: 'cnf-001',
    projectId: 'proj-oil-01',
    activityId: 'act-pipe-0142',
    activityCode: 'PIPE-ERECT-L6-0142',
    activityName: 'Erection of 12-inch process line at compressor area',
    conflictType: 'PROGRESS_CONFLICT',
    severity: 'CRITICAL',
    status: 'UNRESOLVED',
    title: 'Progress Percentage Discrepancy Across Reporting Channels',
    description: 'Supervisor voice dispatch reports 78% completion (18m erected today), whereas the subcontractor evening Excel spreadsheet claims 70% complete. AI prevents automatic overwrite.',
    detectedAt: '2026-09-28T18:05:00Z',
    sources: [
      {
        sourceType: 'VOICE_LOG',
        sourceRef: 'Voice Update #001 (Bikash Gogoi)',
        reportedValue: '78% complete (37.5m / 48m)',
        reporter: 'Bikash Gogoi (Senior Piping Supervisor)',
        timestamp: '2026-09-28 17:15'
      },
      {
        sourceType: 'SPREADSHEET',
        sourceRef: 'AIES_Daily_Subcon_Tracking_28Sep.xlsx [Row 14]',
        reportedValue: '70% complete (33.6m / 48m)',
        reporter: 'AIES Site Coordination Office',
        timestamp: '2026-09-28 18:00'
      }
    ]
  },
  {
    id: 'cnf-002',
    projectId: 'proj-oil-01',
    activityId: 'act-pipe-0144',
    activityCode: 'PIPE-HYDRO-L6-0144',
    activityName: 'Hydrostatic pressure testing of 12-inch process headers',
    conflictType: 'TEMPORAL_CONFLICT',
    severity: 'WARNING',
    status: 'UNRESOLVED',
    title: 'Temporal Sequence Violation: Testing Flagged Before Fit-Up Completion',
    description: 'Field diary draft indicated hydrotest water filling on Line 12 while upstream fit-up & NDT activity (PIPE-FITUP-L6-0143) is only 40% complete. Chronology check failed.',
    detectedAt: '2026-09-28T18:40:00Z',
    sources: [
      {
        sourceType: 'SITE_DIARY_DRAFT',
        sourceRef: 'Field_Log_Area04_28Sep.pdf [Page 2]',
        reportedValue: 'Hydrotest prep filling manifold attached',
        reporter: 'Night Shift Trainee Engineer',
        timestamp: '2026-09-28 18:35'
      }
    ]
  }
];

export const DEMO_TERMINOLOGY_MAPPINGS: TerminologyMapping[] = [
  {
    id: 'term-001',
    projectId: 'proj-oil-01',
    discipline: 'Piping',
    contractor: 'AIES',
    fieldTerm: '12 inch spool erected',
    canonicalActivityCode: 'PIPE-ERECT-L6-0142',
    canonicalActivityName: 'Erection of 12-inch process line at compressor area',
    confidenceBoost: 0.25,
    approvedBy: 'Lead Planner P. Saikia',
    learnedAt: '2026-09-28T18:10:00Z',
    timesApplied: 8
  },
  {
    id: 'term-002',
    projectId: 'proj-oil-01',
    discipline: 'Piping',
    contractor: 'AIES',
    fieldTerm: 'compressor spool install',
    canonicalActivityCode: 'PIPE-ERECT-L6-0142',
    canonicalActivityName: 'Erection of 12-inch process line at compressor area',
    confidenceBoost: 0.20,
    approvedBy: 'Lead Planner P. Saikia',
    learnedAt: '2026-09-27T14:30:00Z',
    timesApplied: 5
  },
  {
    id: 'term-003',
    projectId: 'proj-oil-01',
    discipline: 'Civil',
    contractor: 'North-East Infrastructure',
    fieldTerm: 'F-102 concrete poured',
    canonicalActivityCode: 'CIV-FOUND-L6-0102',
    canonicalActivityName: 'Foundation F-102 concrete pouring and curing',
    confidenceBoost: 0.30,
    approvedBy: 'Lead Planner P. Saikia',
    learnedAt: '2026-09-26T10:00:00Z',
    timesApplied: 12
  },
  {
    id: 'term-004',
    projectId: 'proj-oil-01',
    discipline: 'Electrical',
    contractor: 'Eastern Power Grid Projects',
    fieldTerm: 'tray installation unit 2',
    canonicalActivityCode: 'ELEC-TRAY-L6-0102',
    canonicalActivityName: 'Cable tray installation at Unit 2 compressor bay',
    confidenceBoost: 0.22,
    approvedBy: 'Lead Planner P. Saikia',
    learnedAt: '2026-09-28T16:00:00Z',
    timesApplied: 3
  }
];

export const DEMO_ACTIVITY_DNA: ActivityDNA[] = [
  {
    activityType: 'Pipe Erection (Process Headers 8"-16")',
    discipline: 'Piping',
    typicalDurationDays: 6.8,
    historicalMedianDays: 6.0,
    historicalVarianceDays: 1.4,
    sampleProjectCount: 14,
    synonyms: ['spool erection', 'line erection', 'pipe install', 'spool rigging', 'overhead header erection'],
    primaryDelayCauses: [
      { cause: 'Material delivery / spool fabrication delay', frequencyPct: 42 },
      { cause: 'Crane & heavy rigging availability', frequencyPct: 26 },
      { cause: 'Monsoon weather & work-at-height stoppage', frequencyPct: 18 },
      { cause: 'Alignment fit-up clearance', frequencyPct: 14 }
    ],
    topContractors: [
      { name: 'Assam Industrial Engineering Services (AIES)', performanceRating: 4.1, avgVarianceDays: 1.6 },
      { name: 'Brahmaputra Pipelines Ltd', performanceRating: 4.6, avgVarianceDays: 0.4 },
      { name: 'Bridge & Roof Co. (India)', performanceRating: 4.3, avgVarianceDays: 0.9 }
    ]
  },
  {
    activityType: 'Heavy Equipment Foundation Concreting',
    discipline: 'Civil',
    typicalDurationDays: 12.5,
    historicalMedianDays: 11.8,
    historicalVarianceDays: 2.1,
    sampleProjectCount: 22,
    synonyms: ['foundation pouring', 'plinth casting', 'equipment pad concreting', 'mass concrete pour'],
    primaryDelayCauses: [
      { cause: 'Heavy precipitation & groundwater pumping', frequencyPct: 48 },
      { cause: 'Batching plant transit mixer delays', frequencyPct: 28 },
      { cause: 'Rebar reinforcement inspection hold points', frequencyPct: 15 },
      { cause: 'Curing compound supply', frequencyPct: 9 }
    ],
    topContractors: [
      { name: 'North-East Infrastructure & Infra Corp', performanceRating: 4.4, avgVarianceDays: 1.1 },
      { name: 'L&T Heavy Civil Infra', performanceRating: 4.8, avgVarianceDays: 0.3 }
    ]
  },
  {
    activityType: 'Industrial Cable Tray Installation',
    discipline: 'Electrical',
    typicalDurationDays: 8.5,
    historicalMedianDays: 8.0,
    historicalVarianceDays: 0.9,
    sampleProjectCount: 18,
    synonyms: ['cable tray run', 'raceway installation', 'ladder tray mounting', 'cable duct laying'],
    primaryDelayCauses: [
      { cause: 'Civil handover delay (bracket support clearance)', frequencyPct: 52 },
      { cause: 'Hot work permit issuance', frequencyPct: 24 },
      { cause: 'Hardware fasteners / bend fittings shortage', frequencyPct: 24 }
    ],
    topContractors: [
      { name: 'Eastern Power Grid Projects', performanceRating: 4.2, avgVarianceDays: 1.2 },
      { name: 'Sterling & Wilson Infra', performanceRating: 4.5, avgVarianceDays: 0.5 }
    ]
  }
];

export const DEMO_AUDIT_LOGS: AuditRecord[] = [
  {
    id: 'aud-001',
    timestamp: '2026-09-28T18:10:00Z',
    entityType: 'MATCH',
    entityId: 'match-001',
    action: 'PLANNER_APPROVED_MATCH',
    performedBy: 'Pranjal Saikia',
    role: 'planner',
    details: 'Approved AI proposal linking voice update evt-001 to PIPE-ERECT-L6-0142 with 94% confidence.',
    modelVersion: 'Hybrid-Semantic-v2.4',
    sourceDoc: 'Voice_Audio_Transcribe_001.wav',
    sourcePage: 1,
    oldValue: 'Actual: 58%',
    newValue: 'Actual: 78%'
  },
  {
    id: 'aud-002',
    timestamp: '2026-09-28T18:11:00Z',
    entityType: 'SCHEDULE',
    entityId: 'act-pipe-0142',
    action: 'FORECAST_UPDATE',
    performedBy: 'SiteSync Engine (Automated CPM)',
    role: 'admin',
    details: 'Actual progress update cascaded downstream. Forecast completion moved from 27-Sep to 04-Oct (+7 days delay).',
    modelVersion: 'CPM-CriticalPath-Engine-v1.2',
    oldValue: 'Forecast: 2026-09-27',
    newValue: 'Forecast: 2026-10-04'
  },
  {
    id: 'aud-003',
    timestamp: '2026-09-28T18:12:00Z',
    entityType: 'CONFLICT',
    entityId: 'cnf-001',
    action: 'PROGRESS_CONFLICT_FLAGGED',
    performedBy: 'SiteSync Conflict Engine',
    role: 'admin',
    details: 'Flagged discrepancy: Voice 78% vs Spreadsheet 70%. Retained verified 78% while generating review card for Lead Planner.',
    modelVersion: 'Discrepancy-Classifier-v1.9',
    sourceDoc: 'AIES_Daily_Subcon_Tracking_28Sep.xlsx'
  }
];
